[package]
name = "advent-of-code-2024-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
#memoize = "0.4.2"
anyhow = "1.0.94"
itertools = "0.13.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
chrono = "0.4.31"
chrono-tz = "0.10.0"
regex = { version = "1.11.1", features = [] }
